

rollback work;

begin work;

drop view cgl_cglposteo;
drop view cgl_saldo_aux1;
drop view cxc_cxcfact1;
drop view cxc_hijos;
drop view cxc_madres;
drop view cxp_ajustes_madres;
drop view eys1_eys2_agrupado;
drop view f_conytram_resumen;
drop view fac_facturas;
drop view fac_facturas_cxc;
drop view fac_notas_credito;
drop view fact_despachos;
drop view fact_totales;
drop view fact_ventas;
drop view inv_ventas;
drop view v_bcocircula;
drop view v_cgl_financiero;
drop view v_cgl_presupuesto;
drop view v_cos_traspasos;
drop view v_cxc_resumen_x_dia;
drop view v_cxp_ajustes_hijos;
drop view v_cxp_ajustes_madres;
drop view v_cxp_facturas;
drop view v_cxp_pagos;
drop view v_div_socios;
drop view v_eys1_eys2 cascade;
drop view v_eys1_eys2_x_clase;
drop view v_eys1_eys2_x_mes;
drop view v_eys1_eys2_x_subtipo;
drop view v_eys1_eys2_x_tipo;
drop view v_fact_costos;
drop view v_fact_ventas;
drop view v_fact_ventas_x_clase;
drop view v_fact_ventas_x_clase_detalladas;
drop view v_fact_vtas_detalladas;
drop view v_factura1_factura2;
drop view v_hp_barcos;
drop view v_nomctrac_x_cuenta;
drop view v_nomhoras;
drop view v_oc1_oc2;
drop view v_pla_horas_valorizadas;
drop view v_pla_horas_valorizadas_x_dia;
drop view v_cxc_recibos_madres;
drop view v_cxc_recibos_hijos;
drop view v_cxc_resumen_x_mes;
drop view v_stock;
drop view v_estado_d_resultado;
drop view v_nomctrac_neto;
drop view v_tal_ot2_ot3;
drop view v_pla_acumulados;
drop view v_cxc_empleados_detalle;
drop view v_cxc_empleados_saldos;
drop view v_comprobante_de_pago;
drop view v_pla_historial;
drop view v_pla_reservas_x_departamento;
drop view v_f_conytram;
drop view v_cglsldoaux1;
drop view v_cglposteo;
drop view v_cgl_financiero_x_cuenta;
drop view v_cxpdocm;
drop view v_cxcdocm_cxc;
drop view v_cxcdocm_fac;
drop view v_factura1_cglposteo;
drop view v_afi_trx_cglposteo;
drop view v_eys1_cglposteo;
drop view v_cxpfact1_cglposteo;
drop view v_cgl_financiero_cglsldocuenta;
drop view v_kardex;
drop view v_factura_cglposteo;
drop view v_fac_resumen_z;
drop view v_fact_costos_x_grupo;
drop view v_fac_totales;
drop view v_ventas_x_mes;
drop view v_dividendos_e_intereses;
drop view v_produccion;
drop view v_consumo_trigo;
drop view v_consumo;
drop view v_list_cobros_airsea;
drop view v_ventas_costos;
drop view v_ventas_x_cliente_harinas;
drop view v_fact_ventas_harinas;
drop view v_fact_ventas_harinas_by_date;
drop view v_ventas_x_mes_harinas;
drop view v_cxcdocm_cxchdocm;
drop view v_fac_declaracion_impuestos;
drop view v_cxp_facturas_por_rubros;
drop view v_cxp_declaracion_impuestos;
drop view v_factura1_factura2_x_tdi;
drop view v_cxc_recibos;
drop view v_formulario_43_dgi;
drop view v_cgl_financiero_x_cuenta_detallado;
drop view v_pla_salario_neto;
drop view v_apc_clientes;
drop view v_apc_refere;
drop view v_factura1_factura2_x_cat;
drop view v_cglposteo_detalle_excel;
drop view v_cos_produccion;
drop view v_comprobante_inventario cascade;
drop view v_cxcdocm_fac_fiscal cascade;
drop view v_cgl_presupuesto_detallado;
drop view v_mov_inv_x_sdi cascade;
drop view v_formulario_72_dgi cascade;
drop view v_cglsldoaux2 cascade;
drop view v_cheques;
drop view v_adc_comisiones_verificador;
drop view v_adc_comisiones;
drop view v_adc_estadisticas_house;
drop view v_adc_estadisticas;
drop view v_adc_estadisticas_x_cliente;
drop view v_adc_estadisticas_x_contenedor;
drop view v_adc_estadisticas_venta;
drop view v_adc_facturas_x_master;
drop view v_adc_manifiesto_contable;
drop view v_adc_notificacion;
drop view v_adc_master_cglposteo;
drop view v_adc_house_cglposteo;
drop view v_adc_cxc_1_cglposteo;
drop view v_adc_cxc_1;
drop view v_adc_cxp_1_cglposteo;
drop view v_adc_cxp_1;
drop view v_adc_manifiesto_cliente;
drop view v_adc_si;
drop view v_adc_facturacion;
drop view v_adc_facturacion_carga_suelta;
drop view v_adc_cargas_por_cliente_detallado;
drop view v_adc_verificador_operacion;
drop view v_adc_control_entrega;
drop view v_adc_eficiencia cascade;
drop view v_adc_tracking cascade;
drop view v_adc_notificacion_cargos cascade;
drop view v_adc_verificador_contable cascade;
drop view v_factura1_factura2_airsea cascade;

    
    alter table factura1 alter column nombre_cliente type varchar(100);
    alter table factura1 alter column direccion1 type varchar(100);
    alter table factura1 alter column direccion2 type varchar(100);
    alter table factura1 alter column direccion3 type varchar(100);


commit work;
