rollback work;
begin work;
delete from nom_ajuste_pagos_acreedores;
delete from nomacrem;
delete from nomctrac;
delete from pla_afectacion_contable;
delete from pla_estructura_listado;
delete from pla_preelaborada;
delete from pla_otros_ingresos_fijos;
commit work;

begin work;
delete from bcocheck1;
delete from cglcomprobante1;
delete from cglcomprobante3;
delete from cglcomprobante4;
delete from cglcomprobante1;
delete from cglperiodico3;
delete from cglperiodico4;
delete from factura3;
delete from rela_bcocheck1_cglposteo;
delete from rela_bcotransac1_cglposteo;
delete from rela_afi_cglposteo;
delete from rela_cxcfact1_cglposteo;
delete from rela_cxpajuste1_cglposteo;
delete from rela_cxpfact1_cglposteo;
delete from rela_eys1_cglposteo;
delete from rela_factura1_cglposteo;
delete from rela_caja_trx1_cglposteo;
delete from rela_cxctrx1_cglposteo;
delete from cxpbalance;
delete from bcocircula;
delete from bcobalance;
delete from cglposteo;
delete from cajas_balance;
delete from cxpdocm;
delete from afi_depreciacion where year >= 2001 and periodo >= 1;
delete from invbalance;
commit work;

begin work;
delete from cxcdocm;
delete from cxcbalance;
delete from cglsldocuenta;
delete from cglsldoaux1;
delete from cglsldoaux2;
delete from cxpajuste1;
delete from bcocheck1;
delete from bcotransac1;
delete from eys1;
delete from cxpfact1;
delete from cxcfact1;
delete from cxctrx1;
delete from caja_trx1;
delete from factura1;
delete from oc1;
delete from cxpmorosidad;
delete from cxcmorosidad;
delete from pla_vacacion1;
delete from pla_informe;
delete from nomhrtrab;
delete from nom_conceptos_para_calculo;
delete from nom_otros_ingresos;
delete from facparamcgl;
delete from nomrelac;
delete from nomconce;
commit work;