delete from rela_bcocheck1_cglposteo;
delete from rela_bcotransac1_cglposteo;
delete from dba.cglcomprobante1 where year = 2000 and compania = '03' and aplicacion_origen = 'BCO';
delete from bcocircula where fecha_posteo >= '2000-1-1';
delete from bcobalance;
delete from cglposteo where year = 2000 and compania = '03' and aplicacion_origen = 'BCO';
update bcocheck1 set status = 'R';
update bcotransac1 set status = 'R';
delete from cglsldocuenta where compania = '03' and year = 2000;
delete from cglsldoaux1 where compania = '03' and year = 2000;
delete from cglsldoaux2 where compania = '03' and year = 2000;
update cglcomprobante1 set estado = 'R'  where year = 2000 and compania = '03';
commit;
