vacuum verbose analyze eys1;
vacuum verbose analyze eys2;
vacuum verbose analyze eys3;
vacuum verbose analyze factura1;
vacuum verbose analyze factura2;
vacuum verbose analyze factura4;
vacuum verbose analyze almacen;
vacuum verbose analyze articulos_por_almacen;
vacuum verbose analyze cxctrx1;
vacuum verbose analyze cxctrx2;
vacuum verbose analyze cxctrx3;
vacuum verbose analyze cxcdocm;
vacuum verbose analyze descuentos;
vacuum verbose analyze descuentos_por_grupo;
vacuum verbose analyze descuentos_por_articulo;
vacuum verbose analyze cajas;
vacuum verbose analyze caja_trx1;
vacuum verbose analyze caja_trx2;

